// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anljusqmhznrgqgkddes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFubGp1c3FtaHpucmdxZ2tkZGVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MjEyNDYsImV4cCI6MjA1NDQ5NzI0Nn0.nKG_kSz1yMs78HYvndfwTln1GHX-KnJW-FMfRb_rXTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);